### ISSUE TITLE
No longer works since update 11

### ISSUE THREAD

**Issue by Larkspeed** [peterbn/EDx52display#14]
ED recently upgraded to update 11 and now this no longer works.

It see's the system you are in when you start the game but does not update once you start to jump so always remains on your load system and always says No FSD Target on the display.

**Comment by peterbn** [comment]
Argh - thanks for reporting it. I haven't played ED regularly, but I'll take a look in the not-too-distant future.

**Comment by CMDR-Kegaira-Ohaya** [comment]
Same problem here. Thank you for your hard work, you put the "Joy" in "joystick" :) <3

**Comment by peterbn** [comment]
Hi @Larkspeed and @CMDR-Kegaira-Ohaya.

I just tried a short test flight from Shinrarta Dezra to LHS 2435 and back again (where I was stationed when I logged in).
I saw the information update, both current system and FSD target.
I do not have Odyssey, and it's not inconceivable that there's a difference.

Would you mind doing the following:
1) Start the game and log in to a solo session
2) Make as short a flight as you need to reproduce the problem
3) Log out / exit the game

Then open `%USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous` in the Windows File Explorer and find the latest updated file starting with the name `Journal.` and having the extension `.log`. If you sort by last modified, it should be the file in the folder that was last modified.

Once you've found the file, please attach it to this issue, and I'll have a look.
The 3 test steps ensures that I hopefully get as short a possible a log file to go through.

**Comment by KolaKattz** [comment]
@peterbn I've been having the same issue. It seems to show the system I was in before the update, but it keeps track of my limpets fine. I hope my log can help!
[Journal.2022-03-23T142948.01.log](https://github.com/peterbn/EDx52display/files/8333902/Journal.2022-03-23T142948.01.log)

**Comment by peterbn** [comment]
Thank you for sending the journal file @KolaKattz .

You didn't mention where you were going on that trip, but from reading the log, it looks like you started in `Arietis Sector EL-X b1-5`, then targeted and travelled to `56 Persei` and had `Ngauna` as the next targeted waypoint. 

If that sounds familiar, then I think my code still reads the journal correctly. At least after the fact. So, it's more likely to be a problem that happens when reading the journal file as it's being written.

There could be an issue with the journal file not being written out to disk so the changes aren't visible for the utility to pick up while you are playing, but I don't think that would be the case. 

I did also realise some .. let's say "odd"... choices in architecture in my code that could be the culprit. I might try to rework that part and create a new build, just to see if that solves the problem. Basically, the journal state is global in the program and not cleared before the file is read again, so that could be the source of the problem. It's just odd that it only shows up now.

And I can definitely try to reproduce on my end again.

**Comment by peterbn** [comment]
Ok, I made the architectural changes (see [65a45c6](https://github.com/peterbn/EDx52display/commit/65a45c6041ac7b17147a0d28aea9a4ec344c8015)). 
Here's a new release folder. You can try it out and see if it solves the problem. If so, I'll promote it to an official release. Otherwise, I'll have to come up with a new theory.
[Release.zip](https://github.com/peterbn/EDx52display/files/8337104/Release.zip)

**Comment by KolaKattz** [comment]
Doesn't seemed to have fixed the issue. @peterbn 
It does the same as before, showing the planet I was on when I last switched to Horizons and no FSD target. I forgot to mention before that it shows the error `WARNING: hresult ff040001 (E_PAGENOTACTIVE)` in console.

Could it be something to do with how they changed the file names for the journals? I remember seeing [EDMC had a journal issue](https://github.com/EDCD/EDMarketConnector/pull/1512) with this update aswell.

**Comment by peterbn** [comment]
Thank you for checking @KolaKattz - I did not have high hopes, as what I did _shouldn't_ have made any difference.

But the link to EDMC is much appreciated. I will look closer into it over the weekend and try to apply the same logic.

Looking at the filename of the log file you sent me, it would appear that you are running Odyssey, and the patches from EDMC does mention some difference in file names, so that is likely to be the issue here, and why I cannot reproduce it locally, as I don't have Odyssey. Thankfully the EDMC people have [done the hard work for me](https://github.com/EDCD/EDMarketConnector/blob/main/monitor.py#L264) :smile:

**Comment by peterbn** [comment]
[Release.zip](https://github.com/peterbn/EDx52display/files/8353381/Release.zip)
Here is a new build. It no longer sorts based on file name, which seems to be what fixed it for EDMC. 

Please let me know if it resolves the issue

**Comment by KolaKattz** [comment]
Seems to have worked perfectly, thank you for the fix!

**Comment by CMDR-Kegaira-Ohaya** [comment]
Amazing... You're the best <3

**Comment by Larkspeed** [comment]
Thank you for fixing this, sorry I couldn't take part in the solution after the initial report my health has been bad so I have not been gaming.

**Comment by peterbn** [comment]
Thank you all for trying it out. I hope you get better soon @Larkspeed. I am promoting this to a public release.
