### ISSUE TITLE
Does this work on the X52 Pro

### ISSUE THREAD

**Issue by peejaygee** [peterbn/EDx52display#3]
I have got the files, I have the saitech/logitech drivers installed and I run the .exe, it gives me the command prompt with "2020/04/19 18:44:49 EDx52Display running. Press enter to close." for example and ED and EDMC are running and the files are located in my %%USERPROFILE%% specified in the config, but I don't get anything on my MFD display.

Thoughts?

**Comment by Luk164** [comment]
X52 and x52 pro are identical when it comes to software. So far everything made for x52 has worked on mine. Even the SDK is the same. You are probably doing something wrong.

**Comment by peejaygee** [comment]
What can I be doing wrong? I've followed the instructions, I've unzipped and run the required file, I get some output in the command prompt. Is there a hidden debug command line switch for output? My Antivirus isn't catching anything, and it's a local program, so firewalls wouldn't affect it. Anymore thoughts? What OS are you running it on in particular ? Are you running it on Windows 10 too?

**Comment by peterbn** [comment]
Hi,

I was running it on Windows 8 back when I developed it - I've been away from Elite for some months now. I haven't had an opportunity to test it on Windows 10.

Can you look to see if the tool generates a mfd.json file in the place where you unzipped it? That's the file that controls what's getting written to the display.
If that file is being written with something that seems reasonable (it's just the strings to output), then the problem lies in the "driver" application that's supposed to read the file and put it on the display. 
If the file is empty or not being written, then it's a problem with the logs reader program.

As for debugging flags - err, no, sorry... I kinda just ran the whole thing in debug mode through Visual Studio and Visual Studio Code when developing it.

**Comment by peejaygee** [comment]
Yeah, the file does contain text, so that part is working. I've tried to run both EDx52display.exe and X52MFDDriver.exe in compatibility mode of Windows 8, doesn't help. I know double clicking X52MFDDriver.exe doesnt do anything except flash open a command prompt window real quick (like it's doing something), but if I manually typed in the following into a command prompt window

X52MFDDriver.exe --input mfd.json

and the output I got was.

Loading DirectOutput libaray... DONE.
Initialzing DirectOutput library...  <----- that just sits there.

I'm thinking it's a Windows 10 issue, as I have another X52 display software from elsewhere and it too does the same thing.

If you ever get back into Elite and/or this software, do let me know. Happy to test and/or tweak stuff if you want me to pull your git and compile it through VStudio.

**Comment by peterbn** [comment]
I'd be happy to see if we can get this sorted out.

The code for the driver app is located here: https://github.com/peterbn/X52-pro-MFD-JSON-Driver
It's C++, which is not a language I'm intimately familiar with, but I've done my best to not make it horrible.
The main entry point is in https://github.com/peterbn/X52-pro-MFD-JSON-Driver/blob/master/EliteDangerousX52MFD/EliteDangerousX52MFD/EliteDangerousX52MFD.cpp.

The problem is either the driver, as you say, in which case I don't know enough about drivers and C++ to really help you, or it's in the file change listener so the problem could be that the program simply never reads the json file.
You should be able to set a breakpoint in [onFileChanged](https://github.com/peterbn/X52-pro-MFD-JSON-Driver/blob/master/EliteDangerousX52MFD/EliteDangerousX52MFD/EliteDangerousX52MFD.cpp#L98) and see if the json file gets read in whenever you save it in a different program (use something like notepad++ or similar to simply save the file, you don't need to actually change it).

**Comment by peejaygee** [comment]
Well first and foremost, one day through the week, I'll run the code though my Visual Studio install on Windows 10, it could be a simple recompile that might fix an issue. Then I'll start tweaking/playing with it and see what happens. I too am not full conversed in C++ but have some 'programming/coding' knowledge so it won't look too alien to me. My ultimate plan it to have software like yours for when I'm in 2d, when I'm in my VR I'll not use it, as, well, you can't see the MFD when my vive is on my head. :) [although if you worked on a separate PC output window within the application, that could be cloned into the VR using other software, so that is food for though, but one step at a time]

**Comment by peterbn** [comment]
Awesome, let me know how it goes.

If you are looking for VR setups, I'm pretty sure there are far better screen overlay apps you can use.

**Comment by Luk164** [comment]
@peejaygee BTW I currently use mainly https://github.com/AZaps/Elite-Dangerous-X52-MFD. It is written in C++ so I can actually make changes and I can confirm it works on WIN10

**Comment by peterbn** [comment]
Hi Lukas,

Very curious. My "driver" executable is a fork of AZaps project (https://github.com/peterbn/X52-pro-MFD-JSON-Driver), so I wonder what the difference is. Does my tool work, or is it broken for you too? 

For context, I split my tool in two executables to be able to implement the presentation logic in go instead of c++, but I had to keep the C++ program to talk to the joystick, since I utterly failed to link and use the DLL directly from go.

**Comment by Luk164** [comment]
@peterbn I could run it but there were some problems, but my machine is not good for reference as it is set up with a lot of dev stuff but only a minimum of go. I mainly use the AZaps one because I can make changes to it. GO is not really my language. I also had the same problem you did, where I failed to load the SDK to a C# project.

**Comment by peterbn** [comment]
@Luk164 You don't need to edit the GO project, that seems to be working fine. The problem lies within the second executable, which is a fork of the AZaps application.

**Comment by Luk164** [comment]
@peterbn Yet the AZaps application does work by itself, so something weird is definitely going on.

**Comment by peterbn** [comment]
Hi - sorry for the radio silence. I haven't been able to reproduce the problem on my own. @peejaygee Did you ever get around to running the C++ app from source, and did that reveal anything?

**Comment by peejaygee** [comment]
@peterbn I haven't gotten around to it as of yet, life has been getting in the way and not been on Elite Dangerous in 2d much (been playing off and on in 3d, so can't see the Hotas) but I will get around to it and then I'll come back and let you know my findings. :)

**Comment by peterbn** [comment]
Sounds good. I had a go at running the X52MFDDriver.exe app on my media center pc (which is a win10 PC). 

On that one, there were some issues with the driver.
However, when I went and installed Visual Studio 2019 on that system and tried to debug the program, it worked fine. Thinking I'd solved the problem, I then tried to build the solution and run the resulting executable from the command line, and the problem was back.

I simply don't know enough about C++ and Visual Studio to figure out what the difference is between the two situations. 

@Luk164 if you are still interested in this problem, I have saved a [sample mfd.json file](https://gist.github.com/peterbn/874d1dfd2869aa87a68f33755aca7204) which you can use as input to the https://github.com/peterbn/X52-pro-MFD-JSON-Driver project

**Comment by peterbn** [comment]
Hi.

It's been a long while, but I finally took, a stab at this project again, and I managed to get rid of the weird double-executable dependency. 

There is a new release at https://github.com/peterbn/EDx52display/releases/tag/v1.2

Please give it a go and see if it solves the problem.
