### ISSUE TITLE
MFD is showing cargo, but can't change page.

### ISSUE THREAD

**Issue by olivierpilotte** [peterbn/EDx52display#5]
EDx52display.exe runs fine. But buttons (page up/down) doesn't work. So I've tried to run `X52MFDDriver.exe --input mfd.json` directly and here's the output.

```
> X52MFDDriver.exe --input mfd.json

Loading DirectOutput libaray... DONE.
Initialzing DirectOutput library...
DONE.
Registering device callback...
DONE.
Enumerating devices...
DONE.
Getting device...
Got device X52Pro.
Registering soft button callback...
DONE.
Registering page callback...
DONE.
Reading from JSON file = mfd.json
Adding page...
Adding page...
Adding page...

FindFirstChangeNotification failed.
```

Not sure if it indicates something not working, but I can't change pages. Buttons doesn't seem to have any effect.

**Comment by peterbn** [comment]
Hi,

Thank you for the report.

The short answer is that the program fails at the step where it starts to listen for changes to the mfd.json file, which is how it gets it's updates (https://github.com/peterbn/X52-pro-MFD-JSON-Driver/blob/master/EliteDangerousX52MFD/EliteDangerousX52MFD/EliteDangerousX52MFD.cpp)

Since I was a numpty, I haven't made that code write out a useful error message. 

But, the program stops, which is why the buttons don't do anything.

If you are interested, I can build a new version that prints out the exact error of why it fails, and we can try to get to the bottom of the issue.

**Comment by olivierpilotte** [comment]
Hi,

Any reason why it fails at this step?

Can you indicate how you build the program? Any Makefile?

Thanks,

**Comment by peterbn** [comment]
Sadly, absolutely no idea why it would fail there, assuming that the file exists in the first place. Maybe a Windows permission issue?

My "build process" (and I use that term very loosely) is to build the solution with Visual Studio. The json driver is a separate project, found here: https://github.com/peterbn/X52-pro-MFD-JSON-Driver

C++ is _not_ my preferred language, but I couldn't get Go to link directly to the DirectOutput driver, which is why I ended up with this dual-executable setup.

**Comment by peterbn** [comment]
Ok, I took a look at it, and I _finally_ figured out how to properly interface with the driver directly from go-code.

There is a new release of the display program at https://github.com/peterbn/EDx52display/releases/tag/v1.2

Please give it a go, and see if that fixes your problem.

**Comment by olivierpilotte** [comment]
Awesome! I'll give it a try. Thanks a lot.

**Comment by peterbn** [comment]
Hi oliivierpilotte,

Did the latest version solve the problem?

**Comment by olivierpilotte** [comment]
Hi Peter,

Unfortunately no. When I start `EDx52display.exe`, the correct informations shows up on the MFD (cargo information). Still can't change the pages though.

**Comment by peterbn** [comment]
Hmm... ok, I had hoped it would work.

Are you able to scroll the cargo information up and down with the right wheel?

Are you using the Saitek or the Logitech drivers? And is your HOTAS the Saitek or Logitech branded one?

**Comment by olivierpilotte** [comment]
It works! Page change and scroll within a page works as intended.

I've reinstalled the Logitech Drivers (I had uninstalled them a couple weeks ago to test something).

Thanks Peter!

**Comment by peterbn** [comment]
Great - yeah, my code does require the driver to be installed.

Super happy you got it working. Fly safe, commander.
